#!/bin/sh

case "$1" in
  start)
	echo 0 > /sys/class/pwm/pwmchip0/export
	echo 10000000 > /sys/class/pwm/pwmchip0/pwm0/period
	if [ -f /userdata/system/lcd_backlight ]
	then
		VALUE=$(cat /userdata/system/lcd_backlight)
		echo $VALUE > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
	else
		touch /userdata/system/lcd_backlight
  		echo 000000 > /userdata/system/lcd_backlight
		echo 000000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
	fi
	echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable
	;;
  stop)
	echo 0 > /sys/class/pwm/pwmchip0/pwm0/enable
	echo 0 > /sys/class/pwm/pwmchip0/unexport
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
